// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	log "app/log"

	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Error provides a mock function with given fields: message, err
func (_m *Logger) Error(message string, err error) {
	_m.Called(message, err)
}

// ErrorWithFields provides a mock function with given fields: message, err, fields
func (_m *Logger) ErrorWithFields(message string, err error, fields log.Fields) {
	_m.Called(message, err, fields)
}

// Info provides a mock function with given fields: message
func (_m *Logger) Info(message string) {
	_m.Called(message)
}

// InfoWithFields provides a mock function with given fields: message, fields
func (_m *Logger) InfoWithFields(message string, fields log.Fields) {
	_m.Called(message, fields)
}

// Warn provides a mock function with given fields: message
func (_m *Logger) Warn(message string) {
	_m.Called(message)
}

// WarnWithFields provides a mock function with given fields: message, fields
func (_m *Logger) WarnWithFields(message string, fields log.Fields) {
	_m.Called(message, fields)
}

// WithFields provides a mock function with given fields: fields
func (_m *Logger) WithFields(fields log.Fields) {
	_m.Called(fields)
}
