on:
  push:
    branches:
      - '**'

name: functional-tests
jobs:
  functional-tests:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Code
        run: go test -tags=functional -v ./...